version: '3'
services:
  expense_config:
    build: 
      context: ./expense-config/
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 7000:7000
    container_name: expense_config

  expense_eureka:
    build: 
      context: ./expense-eureka/
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - expense_config
    ports:
      - 8761:8761
    container_name: expense_eureka

  expense_zuul:
    build: 
      context: ./expense-zuul/
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - expense_eureka
    ports:
      - 9761:9761
    container_name: expense_zuul
    command: ["./wait-for-it.sh","expense_eureka:8761","--timeout=100","--","/usr/share/expense/start.sh"]

  expense_stores:
    build: 
      context: ./expense-stores/
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - expense_eureka
    ports:
      - 8083:8083
    container_name: expense_stores
    command: ["./wait-for-it.sh","expense_eureka:8761","--timeout=100","--","/usr/share/expense/start.sh"]

  expense_product:
    build: 
      context: ./expense-product/
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - expense_eureka
    ports:
      - 8081:8081
    container_name: expense_product
    command: ["./wait-for-it.sh","expense_eureka:8761","--timeout=100","--","/usr/share/expense/start.sh"]

  expense_order:
    build: 
      context: ./expense-order/
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - expense_eureka
    ports:
      - 8082:8082
    container_name: expense_order
    command: ["./wait-for-it.sh","expense_eureka:8761","--timeout=100","--","/usr/share/expense/start.sh"]