spring:
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: none
   datasource:
      url: jdbc:mysql://localhost:3306/expense
      username: root
      password: root
server:
   port: 8080
eureka:
   client:
      default-zone: localhost:8761/eureka