spring:
   data:
      mongodb:
         database: expense_db
         host: ds143156.mlab.com
         port: 43156
         username: 
         password: 
server:
   port: 8083
eureka:
   client:
      default-zone: localhost:8761/eureka